services:
  db: 
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - ${BIDGO_DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${BIDGO_DATABASE_USER}
      POSTGRES_PASSWORD: ${BIDGO_DATABASE_PASSWORD}
      POSTGRES_DB: ${BIDGO_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local