// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (product_name, base_price, seller_id, auction_end)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateProductParams struct {
	ProductName string    `json:"product_name"`
	BasePrice   float64   `json:"base_price"`
	SellerID    uuid.UUID `json:"seller_id"`
	AuctionEnd  time.Time `json:"auction_end"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ProductName,
		arg.BasePrice,
		arg.SellerID,
		arg.AuctionEnd,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProductById = `-- name: GetProductById :one
SELECT id, product_name, base_price, seller_id, auction_end, is_sold, created_at, updated_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProductById(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductName,
		&i.BasePrice,
		&i.SellerID,
		&i.AuctionEnd,
		&i.IsSold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, product_name, base_price, seller_id, auction_end, is_sold, created_at, updated_at
FROM products
ORDER BY created_at DESC
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ProductName,
			&i.BasePrice,
			&i.SellerID,
			&i.AuctionEnd,
			&i.IsSold,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsBySeller = `-- name: ListProductsBySeller :many
SELECT id, product_name, base_price, seller_id, auction_end, is_sold, created_at, updated_at
FROM products
WHERE seller_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProductsBySeller(ctx context.Context, sellerID uuid.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsBySeller, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ProductName,
			&i.BasePrice,
			&i.SellerID,
			&i.AuctionEnd,
			&i.IsSold,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET product_name = $2,
    base_price   = $3,
    auction_end  = $4,
    is_sold      = $5,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, product_name, base_price, seller_id, auction_end, is_sold, created_at, updated_at
`

type UpdateProductParams struct {
	ID          uuid.UUID `json:"id"`
	ProductName string    `json:"product_name"`
	BasePrice   float64   `json:"base_price"`
	AuctionEnd  time.Time `json:"auction_end"`
	IsSold      bool      `json:"is_sold"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.ProductName,
		arg.BasePrice,
		arg.AuctionEnd,
		arg.IsSold,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductName,
		&i.BasePrice,
		&i.SellerID,
		&i.AuctionEnd,
		&i.IsSold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
