[database]
port = {{env "BIDGO_DATABASE_PORT"}}
database = {{env "BIDGO_DATABASE_NAME"}}
user = {{env "BIDGO_DATABASE_USER"}}
password = {{env "BIDGO_DATABASE_PASSWORD"}}
host = {{env "BIDGO_DATABASE_HOST"}}